HistoricEngland/arches

releases/5.0.0.md
Initial merge from ArchesProject Stable/5.0.x
=> Initial merge from ArchesProject Stable/5.0.x

.travis.yml, MANIFEST.in, README.md, arches/app/datatypes/datatypes.py, arches/app/media/js/viewmodels/concept-select.js, arches/app/media/js/views/components/datatypes/domain-value.js, arches/app/templates/views/components/datatypes/concept.htm, arches/app/views/main.py, arches/setup.py, releases/5.0.0.md, setup.py
This is the stable branch for 5.0.x just after the release was announced
=> Get Release version of Stable/5.0.x

arches/celery.py
Applying Windows fix for Celery
=> 5915 bug celery fix for windows

arches/management/commands/es.py
=> added argument type to stop type error

arches/app/models/models.py
-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
Within the send_email_on_save function in the model.py file,
```subject, from_email, to = instance.notif.notiftype.name, 'from@example.com', email_to```
has been changed to 
```subject, from_email, to = instance.notif.notiftype.name, settings.DEFAULT_FROM_EMAIL, email_to```
The 'From' email address was hardcoded into ..\arches\arches\app\models\models.py which meant this could not be easily changed according to the requirements of the application.  The change described above now ensures that the 'from' email address either uses the DEFAULT_FROM_EMAIL value in the …
=> Changed from_email input to read from settings

arches/app/views/user.py
-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
Corrected spelling error and changed hardcoded 'Arches' to use settings.APP_NAME instead.
```
message = _(
"Your " + settings.APP_NAME + " profile was just changed.  If this was unexpected, please contact your " + settings.APP_NAME + " administrator at %s."
% (admin_info)
)
user.email_user(_("Your " + settings.APP_NAME + " Profile Has Changed"), message)
```
"You're" rather than "Your" was used in the e-mail subject header so this was corrected.
It wasn't possible to change the application name in the email as it originally was.  By using settings.APP_NAME, the …
=> Email subject change and App Name edit

arches/app/views/search.py
- need to add a minor syntax change
=> fixed the search_export import stub

arches/app/media/css/arches.css, arches/app/templates/views/graph-designer.htm
Further css changes in order to make perfect the title wrapping. Under certain circumstances the title was being cut off. Also removed some unused js which was used for testing.
=> Arches accessibility

arches/app/media/css/arches.css, arches/app/media/css/main.css, arches/app/templates/rdm.htm, arches/app/templates/views/graph-designer.htm, arches/app/templates/views/search.htm
While applying a fix for arches designer buttons being cut off when viewing on smaller screen widths/mobiles etc., I noticed a few other problems and fixed those too...
- Removed some duplicate open source comments to avoid duplicated rendering.
- Fixed some rendering problems on the RDM page (caused by smartadmin css), layout of dropdowns was broke and also the entire left nav menu link/title text was an incorrect font size compared to all other pages, also an unwanted grey box appeared under certain circumstances.
=> Fix for buttons being cut off (bug 24097) and other issues

arches/app/views/api.py
Added support for Arches JSON format in the PUT method of the resources API.
=> Added Json format support to resources PUT

arches/app/media/js/viewmodels/map.js
Fix to limit map searches to gb country only
=> Bug 25122 - Added country code to Mapbox Geocoder

arches/app/media/js/viewmodels/map.js, arches/app/templates/views/components/search/map-filter.htm
Made the drawing cursor a crosshair instead of a hand
=> 23234 make draw cursor crosshair

arches/app/media/css/arches.css
Heading position was incorrect due to a previous change, this fixes the issue.
=> Bug 23594: Fixed heading position

arches/app/media/js/viewmodels/map-editor.js, arches/app/media/js/views/components/cards/select-feature-layers.js, arches/app/media/js/views/components/search/map-filter.js
-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
Addition of ability to change colour of the drawing tools (search filter, geometry editor and map header report template)
Allows customisation of drawing tool symbology
=> 25183 draw tool styling

arches/app/media/js/viewmodels/map-editor.js, arches/app/media/js/views/components/cards/select-feature-layers.js, arches/app/media/js/views/components/search/map-filter.js
=> Promote dev to stage

arches/app/media/js/viewmodels/map-editor.js, arches/app/media/js/views/components/cards/select-feature-layers.js, arches/app/media/js/views/components/search/map-filter.js
=> Promote Stage to Prod - draw tool style

arches/app/datatypes/datatypes.py, arches/app/tasks.py
Removed auto refresh of mv_geojson_geoms from code; this will need to be triggered overnight via a PGAgent job on schedule agreed with the business.
Relates to HE Inventory ticket 28124
=>  Geoms MV no longer auto refreshes

arches/app/datatypes/datatypes.py, arches/app/models/migrations/7012_mv_geojson_add_unique_index.py, arches/app/tasks.py
- Added reverse step to migration of mv_geojson_geoms
- Removed the use of CONCURRENT refresh actions on the mv_geojson_geoms
=> 28174 reverse mv geojson geoms

arches/app/utils/task_management.py
-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
Add ConnectionResetError to exceptionhandling on task_management>check_if_celery_available
#
-   [ ] Unit tests pass locally with my changes
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)
*   Sponsored by: 
*   Found by: @ 
*   Tested by: @ 
*   Designed by: @
=> 30067 KH - handle ConnectionResetError

arches/app/media/js/views/components/search/search-export.js, arches/app/search/search_export.py, arches/app/tasks.py, arches/app/templates/views/components/search/search-export.htm, arches/app/views/api.py, arches/app/views/search.py, arches/settings.py
-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
An option has been added in the Export Search Result panel to allow the user to specify whether or not the full URL to the report of each resource should be added to the CSV or shapefile export.
=> #7541 Addition of option to include report link in CSV or SHP export

arches/app/media/css/arches.scss, arches/app/media/js/viewmodels/resource-instance-select.js, arches/app/templates/views/components/widgets/resource-instance-select.htm
Added fixes to styling of resource-instance-select in the advanced search.
=> 32782 resource select widget icons AB#32782
